name: oyutamaribondo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  audioplayers:
  just_audio: ^0.9.42
  audio_session: ^0.1.21
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.5
  flutter_blue_plus: ^1.34.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  assets:
    - assets/sounds/
  uses-material-design: true
