name: oyutamaribondo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  audioplayers:
  just_audio: ^0.9.42
  audio_session: ^0.1.21
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.5
  flutter_blue_plus: ^1.34.5
  hooks_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  freezed: ^2.5.7
  riverpod_generator: ^2.6.3
  flutter_spinkit: ^5.2.1
  rive: 0.13.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  assets:
    - assets/sounds/audio.mp3
    - assets/sounds/se1.mp3
    - assets/images/
    - assets/animation/
    - assets/sounds/
    - assets/bgm/
    - assets/images/
  uses-material-design: true
